FROM nvcr.io/nvidia/nvhpc:22.5-devel-cuda_multi-ubuntu20.04

# Python 3.10.4 (using deadsnakes PPA)
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get -y install python3.10
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1

# MPICH
RUN apt-get -y install mpich libmpich-dev
